#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 136
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 12
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_quoted_attribute_value_token1 = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_quoted_attribute_value_token2 = 14,
  sym_text = 15,
  anon_sym_DASH_DASH_DASH = 16,
  anon_sym_RBRACE = 17,
  sym__start_tag_name = 18,
  sym__script_start_tag_name = 19,
  sym__style_start_tag_name = 20,
  sym__end_tag_name = 21,
  sym_erroneous_end_tag_name = 22,
  sym__implicit_end_tag = 23,
  sym_raw_text = 24,
  sym_comment = 25,
  sym__frontmatter_start = 26,
  sym__interpolation_start = 27,
  sym__markdown_start_tag_name = 28,
  sym_fragment = 29,
  sym_doctype = 30,
  sym__node = 31,
  sym_element = 32,
  sym_script_element = 33,
  sym_style_element = 34,
  sym_start_tag = 35,
  sym_script_start_tag = 36,
  sym_style_start_tag = 37,
  sym_self_closing_tag = 38,
  sym_end_tag = 39,
  sym_erroneous_end_tag = 40,
  sym_attribute = 41,
  sym_quoted_attribute_value = 42,
  sym_markdown_element = 43,
  sym_markdown_start_tag = 44,
  sym__markdown_self_closing_tag = 45,
  sym_frontmatter = 46,
  sym_interpolation = 47,
  aux_sym_fragment_repeat1 = 48,
  aux_sym_start_tag_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_RBRACE] = "}",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym__frontmatter_start] = "---",
  [sym__interpolation_start] = "{",
  [sym__markdown_start_tag_name] = "tag_name",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_markdown_element] = "markdown_element",
  [sym_markdown_start_tag] = "start_tag",
  [sym__markdown_self_closing_tag] = "self_closing_tag",
  [sym_frontmatter] = "frontmatter",
  [sym_interpolation] = "interpolation",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym__frontmatter_start] = anon_sym_DASH_DASH_DASH,
  [sym__interpolation_start] = sym__interpolation_start,
  [sym__markdown_start_tag_name] = sym__start_tag_name,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_markdown_element] = sym_markdown_element,
  [sym_markdown_start_tag] = sym_start_tag,
  [sym__markdown_self_closing_tag] = sym_self_closing_tag,
  [sym_frontmatter] = sym_frontmatter,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_start] = {
    .visible = true,
    .named = false,
  },
  [sym__interpolation_start] = {
    .visible = true,
    .named = false,
  },
  [sym__markdown_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_element] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__markdown_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 13,
  [21] = 15,
  [22] = 22,
  [23] = 17,
  [24] = 11,
  [25] = 25,
  [26] = 26,
  [27] = 19,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 33,
  [37] = 35,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 26,
  [43] = 43,
  [44] = 22,
  [45] = 45,
  [46] = 28,
  [47] = 12,
  [48] = 29,
  [49] = 39,
  [50] = 45,
  [51] = 30,
  [52] = 40,
  [53] = 32,
  [54] = 34,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 60,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 70,
  [71] = 59,
  [72] = 72,
  [73] = 66,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 78,
  [80] = 76,
  [81] = 75,
  [82] = 39,
  [83] = 13,
  [84] = 39,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 88,
  [94] = 91,
  [95] = 91,
  [96] = 96,
  [97] = 72,
  [98] = 77,
  [99] = 74,
  [100] = 100,
  [101] = 100,
  [102] = 13,
  [103] = 89,
  [104] = 91,
  [105] = 90,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 92,
  [110] = 110,
  [111] = 96,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 114,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 112,
  [123] = 120,
  [124] = 124,
  [125] = 116,
  [126] = 126,
  [127] = 114,
  [128] = 124,
  [129] = 114,
  [130] = 130,
  [131] = 119,
  [132] = 126,
  [133] = 117,
  [134] = 130,
  [135] = 121,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(20);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(18);
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 16, .external_lex_state = 2},
  [2] = {.lex_state = 16, .external_lex_state = 3},
  [3] = {.lex_state = 16, .external_lex_state = 3},
  [4] = {.lex_state = 16, .external_lex_state = 3},
  [5] = {.lex_state = 16, .external_lex_state = 3},
  [6] = {.lex_state = 16, .external_lex_state = 4},
  [7] = {.lex_state = 16, .external_lex_state = 3},
  [8] = {.lex_state = 16, .external_lex_state = 4},
  [9] = {.lex_state = 16, .external_lex_state = 4},
  [10] = {.lex_state = 16, .external_lex_state = 4},
  [11] = {.lex_state = 16, .external_lex_state = 3},
  [12] = {.lex_state = 16, .external_lex_state = 4},
  [13] = {.lex_state = 16, .external_lex_state = 3},
  [14] = {.lex_state = 16, .external_lex_state = 3},
  [15] = {.lex_state = 16, .external_lex_state = 4},
  [16] = {.lex_state = 16, .external_lex_state = 4},
  [17] = {.lex_state = 16, .external_lex_state = 3},
  [18] = {.lex_state = 16, .external_lex_state = 4},
  [19] = {.lex_state = 16, .external_lex_state = 3},
  [20] = {.lex_state = 16, .external_lex_state = 4},
  [21] = {.lex_state = 16, .external_lex_state = 3},
  [22] = {.lex_state = 1, .external_lex_state = 4},
  [23] = {.lex_state = 16, .external_lex_state = 4},
  [24] = {.lex_state = 16, .external_lex_state = 4},
  [25] = {.lex_state = 16, .external_lex_state = 3},
  [26] = {.lex_state = 16, .external_lex_state = 3},
  [27] = {.lex_state = 16, .external_lex_state = 4},
  [28] = {.lex_state = 16, .external_lex_state = 3},
  [29] = {.lex_state = 16, .external_lex_state = 3},
  [30] = {.lex_state = 16, .external_lex_state = 3},
  [31] = {.lex_state = 16, .external_lex_state = 4},
  [32] = {.lex_state = 16, .external_lex_state = 3},
  [33] = {.lex_state = 16, .external_lex_state = 4},
  [34] = {.lex_state = 16, .external_lex_state = 3},
  [35] = {.lex_state = 16, .external_lex_state = 4},
  [36] = {.lex_state = 16, .external_lex_state = 3},
  [37] = {.lex_state = 16, .external_lex_state = 3},
  [38] = {.lex_state = 16, .external_lex_state = 4},
  [39] = {.lex_state = 16, .external_lex_state = 4},
  [40] = {.lex_state = 16, .external_lex_state = 3},
  [41] = {.lex_state = 16, .external_lex_state = 3},
  [42] = {.lex_state = 16, .external_lex_state = 4},
  [43] = {.lex_state = 16, .external_lex_state = 3},
  [44] = {.lex_state = 1, .external_lex_state = 4},
  [45] = {.lex_state = 16, .external_lex_state = 3},
  [46] = {.lex_state = 16, .external_lex_state = 4},
  [47] = {.lex_state = 16, .external_lex_state = 3},
  [48] = {.lex_state = 16, .external_lex_state = 4},
  [49] = {.lex_state = 16, .external_lex_state = 3},
  [50] = {.lex_state = 16, .external_lex_state = 4},
  [51] = {.lex_state = 16, .external_lex_state = 4},
  [52] = {.lex_state = 16, .external_lex_state = 4},
  [53] = {.lex_state = 16, .external_lex_state = 4},
  [54] = {.lex_state = 16, .external_lex_state = 4},
  [55] = {.lex_state = 6, .external_lex_state = 5},
  [56] = {.lex_state = 6, .external_lex_state = 5},
  [57] = {.lex_state = 6, .external_lex_state = 5},
  [58] = {.lex_state = 6, .external_lex_state = 5},
  [59] = {.lex_state = 6, .external_lex_state = 5},
  [60] = {.lex_state = 6, .external_lex_state = 5},
  [61] = {.lex_state = 6, .external_lex_state = 5},
  [62] = {.lex_state = 6, .external_lex_state = 5},
  [63] = {.lex_state = 6, .external_lex_state = 5},
  [64] = {.lex_state = 6, .external_lex_state = 6},
  [65] = {.lex_state = 6, .external_lex_state = 6},
  [66] = {.lex_state = 6, .external_lex_state = 5},
  [67] = {.lex_state = 0, .external_lex_state = 7},
  [68] = {.lex_state = 0, .external_lex_state = 7},
  [69] = {.lex_state = 6, .external_lex_state = 6},
  [70] = {.lex_state = 6, .external_lex_state = 6},
  [71] = {.lex_state = 6, .external_lex_state = 6},
  [72] = {.lex_state = 6, .external_lex_state = 5},
  [73] = {.lex_state = 6, .external_lex_state = 6},
  [74] = {.lex_state = 6, .external_lex_state = 5},
  [75] = {.lex_state = 0, .external_lex_state = 8},
  [76] = {.lex_state = 0, .external_lex_state = 8},
  [77] = {.lex_state = 6, .external_lex_state = 5},
  [78] = {.lex_state = 0, .external_lex_state = 8},
  [79] = {.lex_state = 0, .external_lex_state = 8},
  [80] = {.lex_state = 0, .external_lex_state = 8},
  [81] = {.lex_state = 0, .external_lex_state = 8},
  [82] = {.lex_state = 6, .external_lex_state = 5},
  [83] = {.lex_state = 6, .external_lex_state = 5},
  [84] = {.lex_state = 6, .external_lex_state = 6},
  [85] = {.lex_state = 0, .external_lex_state = 8},
  [86] = {.lex_state = 0, .external_lex_state = 8},
  [87] = {.lex_state = 0, .external_lex_state = 8},
  [88] = {.lex_state = 0, .external_lex_state = 9},
  [89] = {.lex_state = 0, .external_lex_state = 6},
  [90] = {.lex_state = 0, .external_lex_state = 6},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 0, .external_lex_state = 6},
  [93] = {.lex_state = 0, .external_lex_state = 9},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 0, .external_lex_state = 8},
  [96] = {.lex_state = 2, .external_lex_state = 6},
  [97] = {.lex_state = 6, .external_lex_state = 6},
  [98] = {.lex_state = 6, .external_lex_state = 6},
  [99] = {.lex_state = 6, .external_lex_state = 6},
  [100] = {.lex_state = 3, .external_lex_state = 6},
  [101] = {.lex_state = 3, .external_lex_state = 6},
  [102] = {.lex_state = 6, .external_lex_state = 6},
  [103] = {.lex_state = 0, .external_lex_state = 6},
  [104] = {.lex_state = 0, .external_lex_state = 8},
  [105] = {.lex_state = 0, .external_lex_state = 6},
  [106] = {.lex_state = 0, .external_lex_state = 8},
  [107] = {.lex_state = 0, .external_lex_state = 8},
  [108] = {.lex_state = 0, .external_lex_state = 8},
  [109] = {.lex_state = 0, .external_lex_state = 6},
  [110] = {.lex_state = 0, .external_lex_state = 8},
  [111] = {.lex_state = 2, .external_lex_state = 6},
  [112] = {.lex_state = 0, .external_lex_state = 6},
  [113] = {.lex_state = 0, .external_lex_state = 6},
  [114] = {.lex_state = 0, .external_lex_state = 6},
  [115] = {.lex_state = 0, .external_lex_state = 6},
  [116] = {.lex_state = 0, .external_lex_state = 6},
  [117] = {.lex_state = 0, .external_lex_state = 6},
  [118] = {.lex_state = 0, .external_lex_state = 6},
  [119] = {.lex_state = 0, .external_lex_state = 10},
  [120] = {.lex_state = 0, .external_lex_state = 6},
  [121] = {.lex_state = 0, .external_lex_state = 6},
  [122] = {.lex_state = 0, .external_lex_state = 6},
  [123] = {.lex_state = 0, .external_lex_state = 6},
  [124] = {.lex_state = 0, .external_lex_state = 6},
  [125] = {.lex_state = 0, .external_lex_state = 6},
  [126] = {.lex_state = 15, .external_lex_state = 6},
  [127] = {.lex_state = 0, .external_lex_state = 6},
  [128] = {.lex_state = 0, .external_lex_state = 6},
  [129] = {.lex_state = 0, .external_lex_state = 6},
  [130] = {.lex_state = 0, .external_lex_state = 11},
  [131] = {.lex_state = 0, .external_lex_state = 10},
  [132] = {.lex_state = 15, .external_lex_state = 6},
  [133] = {.lex_state = 0, .external_lex_state = 6},
  [134] = {.lex_state = 0, .external_lex_state = 11},
  [135] = {.lex_state = 0, .external_lex_state = 6},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
  ts_external_token__frontmatter_start = 9,
  ts_external_token__interpolation_start = 10,
  ts_external_token__markdown_start_tag_name = 11,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token__frontmatter_start] = sym__frontmatter_start,
  [ts_external_token__interpolation_start] = sym__interpolation_start,
  [ts_external_token__markdown_start_tag_name] = sym__markdown_start_tag_name,
};

static const bool ts_external_scanner_states[12][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token__interpolation_start] = true,
    [ts_external_token__markdown_start_tag_name] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token__interpolation_start] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
  },
  [4] = {
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
  },
  [5] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token__markdown_start_tag_name] = true,
  },
  [8] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [11] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__frontmatter_start] = ACTIONS(1),
    [sym__interpolation_start] = ACTIONS(1),
    [sym__markdown_start_tag_name] = ACTIONS(1),
  },
  [1] = {
    [sym_fragment] = STATE(113),
    [sym_doctype] = STATE(6),
    [sym__node] = STATE(6),
    [sym_element] = STATE(6),
    [sym_script_element] = STATE(6),
    [sym_style_element] = STATE(6),
    [sym_start_tag] = STATE(4),
    [sym_script_start_tag] = STATE(75),
    [sym_style_start_tag] = STATE(76),
    [sym_self_closing_tag] = STATE(15),
    [sym_erroneous_end_tag] = STATE(6),
    [sym_markdown_element] = STATE(6),
    [sym_markdown_start_tag] = STATE(78),
    [sym__markdown_self_closing_tag] = STATE(16),
    [sym_frontmatter] = STATE(10),
    [sym_interpolation] = STATE(6),
    [aux_sym_fragment_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym__frontmatter_start] = ACTIONS(15),
    [sym__interpolation_start] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    ACTIONS(25), 1,
      sym_text,
    ACTIONS(27), 1,
      sym__implicit_end_tag,
    ACTIONS(29), 1,
      sym__interpolation_start,
    STATE(2), 1,
      sym_start_tag,
    STATE(14), 1,
      sym__markdown_self_closing_tag,
    STATE(19), 1,
      sym_end_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(79), 1,
      sym_markdown_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 1,
      sym_script_start_tag,
    STATE(3), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [54] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym__interpolation_start,
    ACTIONS(31), 1,
      sym_text,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(14), 1,
      sym__markdown_self_closing_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(34), 1,
      sym_end_tag,
    STATE(79), 1,
      sym_markdown_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 1,
      sym_script_start_tag,
    STATE(7), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [108] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      sym__interpolation_start,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym_text,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(14), 1,
      sym__markdown_self_closing_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(27), 1,
      sym_end_tag,
    STATE(79), 1,
      sym_markdown_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 1,
      sym_script_start_tag,
    STATE(5), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [162] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      sym__interpolation_start,
    ACTIONS(31), 1,
      sym_text,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    ACTIONS(41), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(14), 1,
      sym__markdown_self_closing_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(54), 1,
      sym_end_tag,
    STATE(79), 1,
      sym_markdown_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 1,
      sym_script_start_tag,
    STATE(7), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [216] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      sym__interpolation_start,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(16), 1,
      sym__markdown_self_closing_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(76), 1,
      sym_style_start_tag,
    STATE(78), 1,
      sym_markdown_start_tag,
    STATE(8), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [267] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LT_BANG,
    ACTIONS(50), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LT_SLASH,
    ACTIONS(56), 1,
      sym_text,
    ACTIONS(59), 1,
      sym__implicit_end_tag,
    ACTIONS(61), 1,
      sym__interpolation_start,
    STATE(2), 1,
      sym_start_tag,
    STATE(14), 1,
      sym__markdown_self_closing_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(79), 1,
      sym_markdown_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 1,
      sym_script_start_tag,
    STATE(7), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [318] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      anon_sym_LT_BANG,
    ACTIONS(67), 1,
      anon_sym_LT,
    ACTIONS(70), 1,
      anon_sym_LT_SLASH,
    ACTIONS(73), 1,
      sym_text,
    ACTIONS(76), 1,
      sym__interpolation_start,
    STATE(4), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(16), 1,
      sym__markdown_self_closing_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(76), 1,
      sym_style_start_tag,
    STATE(78), 1,
      sym_markdown_start_tag,
    STATE(8), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [369] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      sym__interpolation_start,
    ACTIONS(45), 1,
      sym_text,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(16), 1,
      sym__markdown_self_closing_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(76), 1,
      sym_style_start_tag,
    STATE(78), 1,
      sym_markdown_start_tag,
    STATE(8), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [420] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      sym__interpolation_start,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(16), 1,
      sym__markdown_self_closing_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(76), 1,
      sym_style_start_tag,
    STATE(78), 1,
      sym_markdown_start_tag,
    STATE(9), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_markdown_element,
      sym_interpolation,
      aux_sym_fragment_repeat1,
  [471] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(83), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [485] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LT,
    ACTIONS(87), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [499] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(91), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_LT,
    ACTIONS(95), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [527] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LT,
    ACTIONS(99), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [541] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_LT,
    ACTIONS(95), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [555] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LT,
    ACTIONS(103), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [569] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_LT,
    ACTIONS(107), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_LT,
    ACTIONS(111), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [597] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(91), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [611] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LT,
    ACTIONS(99), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [625] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_attribute_value,
    ACTIONS(117), 1,
      anon_sym_SQUOTE,
    ACTIONS(119), 1,
      anon_sym_DQUOTE,
    ACTIONS(121), 1,
      sym__interpolation_start,
    STATE(97), 2,
      sym_quoted_attribute_value,
      sym_interpolation,
  [645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LT,
    ACTIONS(103), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(83), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [673] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_LT,
    ACTIONS(123), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [687] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LT,
    ACTIONS(127), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [701] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_LT,
    ACTIONS(111), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(131), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [729] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_LT,
    ACTIONS(135), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [743] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_LT,
    ACTIONS(139), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [757] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_LT,
    ACTIONS(123), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_LT,
    ACTIONS(143), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [785] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LT,
    ACTIONS(147), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [799] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_LT,
    ACTIONS(151), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [813] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(155), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LT,
    ACTIONS(147), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [841] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(155), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [855] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LT,
    ACTIONS(159), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [869] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(163), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [883] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_LT,
    ACTIONS(167), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [897] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_LT,
    ACTIONS(171), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [911] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LT,
    ACTIONS(127), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [925] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_LT,
    ACTIONS(175), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [939] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym_attribute_value,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      sym__interpolation_start,
    STATE(72), 2,
      sym_quoted_attribute_value,
      sym_interpolation,
  [959] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LT,
    ACTIONS(187), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [973] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(131), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LT,
    ACTIONS(87), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1001] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_LT,
    ACTIONS(135), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1015] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(163), 5,
      sym__implicit_end_tag,
      sym__interpolation_start,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1029] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LT,
    ACTIONS(187), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1043] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_LT,
    ACTIONS(139), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1057] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_LT,
    ACTIONS(167), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1071] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_LT,
    ACTIONS(143), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1085] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_LT,
    ACTIONS(151), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [1099] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_GT,
    ACTIONS(193), 1,
      anon_sym_SLASH_GT,
    ACTIONS(195), 1,
      sym_attribute_name,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1116] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(197), 1,
      anon_sym_SLASH_GT,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1133] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(199), 1,
      anon_sym_GT,
    ACTIONS(201), 1,
      anon_sym_SLASH_GT,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1150] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(199), 1,
      anon_sym_GT,
    ACTIONS(203), 1,
      anon_sym_SLASH_GT,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1167] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_attribute_name,
    ACTIONS(205), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1182] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(210), 1,
      anon_sym_GT,
    ACTIONS(212), 1,
      anon_sym_SLASH_GT,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1199] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(214), 1,
      anon_sym_GT,
    ACTIONS(216), 1,
      anon_sym_SLASH_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1216] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(214), 1,
      anon_sym_GT,
    ACTIONS(218), 1,
      anon_sym_SLASH_GT,
    STATE(58), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1233] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(210), 1,
      anon_sym_GT,
    ACTIONS(220), 1,
      anon_sym_SLASH_GT,
    STATE(55), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1250] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_GT,
    ACTIONS(224), 1,
      sym_attribute_name,
    STATE(71), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1264] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_attribute_name,
    ACTIONS(226), 1,
      anon_sym_GT,
    STATE(71), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1278] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_EQ,
    ACTIONS(228), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1290] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym__start_tag_name,
    ACTIONS(234), 1,
      sym__script_start_tag_name,
    ACTIONS(236), 1,
      sym__style_start_tag_name,
    ACTIONS(238), 1,
      sym__markdown_start_tag_name,
  [1306] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym__script_start_tag_name,
    ACTIONS(236), 1,
      sym__style_start_tag_name,
    ACTIONS(240), 1,
      sym__start_tag_name,
    ACTIONS(242), 1,
      sym__markdown_start_tag_name,
  [1322] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_attribute_name,
    ACTIONS(244), 1,
      anon_sym_GT,
    STATE(64), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1336] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_attribute_name,
    ACTIONS(246), 1,
      anon_sym_GT,
    STATE(65), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1350] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_GT,
    ACTIONS(248), 1,
      sym_attribute_name,
    STATE(71), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1373] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_EQ,
    ACTIONS(228), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1393] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    ACTIONS(259), 1,
      sym_raw_text,
    STATE(31), 1,
      sym_end_tag,
  [1406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    ACTIONS(261), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_end_tag,
  [1419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1428] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    ACTIONS(265), 1,
      sym_raw_text,
    STATE(35), 1,
      sym_end_tag,
  [1441] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    ACTIONS(269), 1,
      sym_raw_text,
    STATE(37), 1,
      sym_end_tag,
  [1454] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    ACTIONS(271), 1,
      sym_raw_text,
    STATE(36), 1,
      sym_end_tag,
  [1467] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    ACTIONS(273), 1,
      sym_raw_text,
    STATE(25), 1,
      sym_end_tag,
  [1480] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1506] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(277), 1,
      sym_raw_text,
  [1516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1532] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym__end_tag_name,
    ACTIONS(285), 1,
      sym_erroneous_end_tag_name,
  [1542] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    STATE(48), 1,
      sym_end_tag,
  [1552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    STATE(51), 1,
      sym_end_tag,
  [1562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
    ACTIONS(289), 1,
      sym_raw_text,
  [1572] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    STATE(53), 1,
      sym_end_tag,
  [1582] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(291), 1,
      sym__end_tag_name,
  [1592] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_RBRACE,
    ACTIONS(295), 1,
      sym_raw_text,
  [1602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_RBRACE,
    ACTIONS(299), 1,
      sym_raw_text,
  [1612] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
    ACTIONS(303), 1,
      aux_sym_quoted_attribute_value_token2,
  [1622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1630] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1638] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1646] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_SQUOTE,
    ACTIONS(307), 1,
      aux_sym_quoted_attribute_value_token1,
  [1656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_SQUOTE,
    ACTIONS(309), 1,
      aux_sym_quoted_attribute_value_token1,
  [1666] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1674] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    STATE(29), 1,
      sym_end_tag,
  [1684] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
    ACTIONS(313), 1,
      sym_raw_text,
  [1694] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    STATE(30), 1,
      sym_end_tag,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1712] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1728] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    STATE(32), 1,
      sym_end_tag,
  [1738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1746] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    ACTIONS(323), 1,
      aux_sym_quoted_attribute_value_token2,
  [1756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_SQUOTE,
  [1763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      ts_builtin_sym_end,
  [1770] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
  [1777] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_DASH_DASH_DASH,
  [1784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_DQUOTE,
  [1791] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_GT,
  [1798] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
  [1805] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      sym_erroneous_end_tag_name,
  [1812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_GT,
  [1819] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym__doctype,
  [1826] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_SQUOTE,
  [1833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_GT,
  [1840] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_GT,
  [1847] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_DQUOTE,
  [1854] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      aux_sym_doctype_token1,
  [1861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_RBRACE,
  [1868] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_GT,
  [1875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_RBRACE,
  [1882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym__end_tag_name,
  [1889] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_erroneous_end_tag_name,
  [1896] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      aux_sym_doctype_token1,
  [1903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_GT,
  [1910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym__end_tag_name,
  [1917] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 162,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 267,
  [SMALL_STATE(8)] = 318,
  [SMALL_STATE(9)] = 369,
  [SMALL_STATE(10)] = 420,
  [SMALL_STATE(11)] = 471,
  [SMALL_STATE(12)] = 485,
  [SMALL_STATE(13)] = 499,
  [SMALL_STATE(14)] = 513,
  [SMALL_STATE(15)] = 527,
  [SMALL_STATE(16)] = 541,
  [SMALL_STATE(17)] = 555,
  [SMALL_STATE(18)] = 569,
  [SMALL_STATE(19)] = 583,
  [SMALL_STATE(20)] = 597,
  [SMALL_STATE(21)] = 611,
  [SMALL_STATE(22)] = 625,
  [SMALL_STATE(23)] = 645,
  [SMALL_STATE(24)] = 659,
  [SMALL_STATE(25)] = 673,
  [SMALL_STATE(26)] = 687,
  [SMALL_STATE(27)] = 701,
  [SMALL_STATE(28)] = 715,
  [SMALL_STATE(29)] = 729,
  [SMALL_STATE(30)] = 743,
  [SMALL_STATE(31)] = 757,
  [SMALL_STATE(32)] = 771,
  [SMALL_STATE(33)] = 785,
  [SMALL_STATE(34)] = 799,
  [SMALL_STATE(35)] = 813,
  [SMALL_STATE(36)] = 827,
  [SMALL_STATE(37)] = 841,
  [SMALL_STATE(38)] = 855,
  [SMALL_STATE(39)] = 869,
  [SMALL_STATE(40)] = 883,
  [SMALL_STATE(41)] = 897,
  [SMALL_STATE(42)] = 911,
  [SMALL_STATE(43)] = 925,
  [SMALL_STATE(44)] = 939,
  [SMALL_STATE(45)] = 959,
  [SMALL_STATE(46)] = 973,
  [SMALL_STATE(47)] = 987,
  [SMALL_STATE(48)] = 1001,
  [SMALL_STATE(49)] = 1015,
  [SMALL_STATE(50)] = 1029,
  [SMALL_STATE(51)] = 1043,
  [SMALL_STATE(52)] = 1057,
  [SMALL_STATE(53)] = 1071,
  [SMALL_STATE(54)] = 1085,
  [SMALL_STATE(55)] = 1099,
  [SMALL_STATE(56)] = 1116,
  [SMALL_STATE(57)] = 1133,
  [SMALL_STATE(58)] = 1150,
  [SMALL_STATE(59)] = 1167,
  [SMALL_STATE(60)] = 1182,
  [SMALL_STATE(61)] = 1199,
  [SMALL_STATE(62)] = 1216,
  [SMALL_STATE(63)] = 1233,
  [SMALL_STATE(64)] = 1250,
  [SMALL_STATE(65)] = 1264,
  [SMALL_STATE(66)] = 1278,
  [SMALL_STATE(67)] = 1290,
  [SMALL_STATE(68)] = 1306,
  [SMALL_STATE(69)] = 1322,
  [SMALL_STATE(70)] = 1336,
  [SMALL_STATE(71)] = 1350,
  [SMALL_STATE(72)] = 1364,
  [SMALL_STATE(73)] = 1373,
  [SMALL_STATE(74)] = 1384,
  [SMALL_STATE(75)] = 1393,
  [SMALL_STATE(76)] = 1406,
  [SMALL_STATE(77)] = 1419,
  [SMALL_STATE(78)] = 1428,
  [SMALL_STATE(79)] = 1441,
  [SMALL_STATE(80)] = 1454,
  [SMALL_STATE(81)] = 1467,
  [SMALL_STATE(82)] = 1480,
  [SMALL_STATE(83)] = 1489,
  [SMALL_STATE(84)] = 1498,
  [SMALL_STATE(85)] = 1506,
  [SMALL_STATE(86)] = 1516,
  [SMALL_STATE(87)] = 1524,
  [SMALL_STATE(88)] = 1532,
  [SMALL_STATE(89)] = 1542,
  [SMALL_STATE(90)] = 1552,
  [SMALL_STATE(91)] = 1562,
  [SMALL_STATE(92)] = 1572,
  [SMALL_STATE(93)] = 1582,
  [SMALL_STATE(94)] = 1592,
  [SMALL_STATE(95)] = 1602,
  [SMALL_STATE(96)] = 1612,
  [SMALL_STATE(97)] = 1622,
  [SMALL_STATE(98)] = 1630,
  [SMALL_STATE(99)] = 1638,
  [SMALL_STATE(100)] = 1646,
  [SMALL_STATE(101)] = 1656,
  [SMALL_STATE(102)] = 1666,
  [SMALL_STATE(103)] = 1674,
  [SMALL_STATE(104)] = 1684,
  [SMALL_STATE(105)] = 1694,
  [SMALL_STATE(106)] = 1704,
  [SMALL_STATE(107)] = 1712,
  [SMALL_STATE(108)] = 1720,
  [SMALL_STATE(109)] = 1728,
  [SMALL_STATE(110)] = 1738,
  [SMALL_STATE(111)] = 1746,
  [SMALL_STATE(112)] = 1756,
  [SMALL_STATE(113)] = 1763,
  [SMALL_STATE(114)] = 1770,
  [SMALL_STATE(115)] = 1777,
  [SMALL_STATE(116)] = 1784,
  [SMALL_STATE(117)] = 1791,
  [SMALL_STATE(118)] = 1798,
  [SMALL_STATE(119)] = 1805,
  [SMALL_STATE(120)] = 1812,
  [SMALL_STATE(121)] = 1819,
  [SMALL_STATE(122)] = 1826,
  [SMALL_STATE(123)] = 1833,
  [SMALL_STATE(124)] = 1840,
  [SMALL_STATE(125)] = 1847,
  [SMALL_STATE(126)] = 1854,
  [SMALL_STATE(127)] = 1861,
  [SMALL_STATE(128)] = 1868,
  [SMALL_STATE(129)] = 1875,
  [SMALL_STATE(130)] = 1882,
  [SMALL_STATE(131)] = 1889,
  [SMALL_STATE(132)] = 1896,
  [SMALL_STATE(133)] = 1903,
  [SMALL_STATE(134)] = 1910,
  [SMALL_STATE(135)] = 1917,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(135),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(68),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(131),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(104),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(121),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(67),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(119),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(8),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(91),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__markdown_self_closing_tag, 4),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__markdown_self_closing_tag, 4),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_element, 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_element, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_element, 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_element, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_element, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_element, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__markdown_self_closing_tag, 3),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__markdown_self_closing_tag, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(66),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(73),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_start_tag, 4),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_start_tag, 3),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [327] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_astro_external_scanner_create(void);
void tree_sitter_astro_external_scanner_destroy(void *);
bool tree_sitter_astro_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_astro_external_scanner_serialize(void *, char *);
void tree_sitter_astro_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_astro(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_astro_external_scanner_create,
      tree_sitter_astro_external_scanner_destroy,
      tree_sitter_astro_external_scanner_scan,
      tree_sitter_astro_external_scanner_serialize,
      tree_sitter_astro_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
