#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_quoted_attribute_value_token1 = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_quoted_attribute_value_token2 = 14,
  sym_text = 15,
  anon_sym_DASH_DASH_DASH = 16,
  sym__frontmatter_start = 17,
  sym__start_tag_name = 18,
  sym__script_start_tag_name = 19,
  sym__style_start_tag_name = 20,
  sym__end_tag_name = 21,
  sym_erroneous_end_tag_name = 22,
  sym__implicit_end_tag = 23,
  sym_raw_text = 24,
  sym_comment = 25,
  sym_fragment = 26,
  sym_doctype = 27,
  sym__node = 28,
  sym_element = 29,
  sym_script_element = 30,
  sym_style_element = 31,
  sym_start_tag = 32,
  sym_script_start_tag = 33,
  sym_style_start_tag = 34,
  sym_self_closing_tag = 35,
  sym_end_tag = 36,
  sym_erroneous_end_tag = 37,
  sym_attribute = 38,
  sym_quoted_attribute_value = 39,
  sym_frontmatter = 40,
  aux_sym_fragment_repeat1 = 41,
  aux_sym_start_tag_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [anon_sym_DASH_DASH_DASH] = "---",
  [sym__frontmatter_start] = "---",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_frontmatter] = "frontmatter",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [sym__frontmatter_start] = anon_sym_DASH_DASH_DASH,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_frontmatter] = sym_frontmatter,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym__frontmatter_start] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(35);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 15, .external_lex_state = 2},
  [2] = {.lex_state = 15, .external_lex_state = 3},
  [3] = {.lex_state = 15, .external_lex_state = 3},
  [4] = {.lex_state = 15, .external_lex_state = 3},
  [5] = {.lex_state = 15, .external_lex_state = 3},
  [6] = {.lex_state = 15, .external_lex_state = 4},
  [7] = {.lex_state = 15, .external_lex_state = 3},
  [8] = {.lex_state = 15, .external_lex_state = 4},
  [9] = {.lex_state = 15, .external_lex_state = 4},
  [10] = {.lex_state = 15, .external_lex_state = 4},
  [11] = {.lex_state = 15, .external_lex_state = 4},
  [12] = {.lex_state = 15, .external_lex_state = 3},
  [13] = {.lex_state = 6, .external_lex_state = 5},
  [14] = {.lex_state = 15, .external_lex_state = 3},
  [15] = {.lex_state = 15, .external_lex_state = 3},
  [16] = {.lex_state = 15, .external_lex_state = 4},
  [17] = {.lex_state = 6, .external_lex_state = 5},
  [18] = {.lex_state = 15, .external_lex_state = 4},
  [19] = {.lex_state = 15, .external_lex_state = 3},
  [20] = {.lex_state = 6, .external_lex_state = 5},
  [21] = {.lex_state = 15, .external_lex_state = 3},
  [22] = {.lex_state = 15, .external_lex_state = 3},
  [23] = {.lex_state = 15, .external_lex_state = 4},
  [24] = {.lex_state = 15, .external_lex_state = 4},
  [25] = {.lex_state = 15, .external_lex_state = 3},
  [26] = {.lex_state = 6, .external_lex_state = 5},
  [27] = {.lex_state = 15, .external_lex_state = 4},
  [28] = {.lex_state = 15, .external_lex_state = 3},
  [29] = {.lex_state = 15, .external_lex_state = 4},
  [30] = {.lex_state = 15, .external_lex_state = 3},
  [31] = {.lex_state = 15, .external_lex_state = 3},
  [32] = {.lex_state = 15, .external_lex_state = 3},
  [33] = {.lex_state = 15, .external_lex_state = 4},
  [34] = {.lex_state = 15, .external_lex_state = 4},
  [35] = {.lex_state = 6, .external_lex_state = 5},
  [36] = {.lex_state = 15, .external_lex_state = 3},
  [37] = {.lex_state = 15, .external_lex_state = 4},
  [38] = {.lex_state = 15, .external_lex_state = 3},
  [39] = {.lex_state = 15, .external_lex_state = 4},
  [40] = {.lex_state = 15, .external_lex_state = 4},
  [41] = {.lex_state = 15, .external_lex_state = 3},
  [42] = {.lex_state = 15, .external_lex_state = 4},
  [43] = {.lex_state = 15, .external_lex_state = 4},
  [44] = {.lex_state = 6, .external_lex_state = 4},
  [45] = {.lex_state = 6, .external_lex_state = 4},
  [46] = {.lex_state = 1, .external_lex_state = 4},
  [47] = {.lex_state = 6, .external_lex_state = 5},
  [48] = {.lex_state = 6, .external_lex_state = 4},
  [49] = {.lex_state = 6, .external_lex_state = 4},
  [50] = {.lex_state = 6, .external_lex_state = 4},
  [51] = {.lex_state = 1, .external_lex_state = 4},
  [52] = {.lex_state = 0, .external_lex_state = 6},
  [53] = {.lex_state = 0, .external_lex_state = 6},
  [54] = {.lex_state = 0, .external_lex_state = 7},
  [55] = {.lex_state = 6, .external_lex_state = 5},
  [56] = {.lex_state = 6, .external_lex_state = 5},
  [57] = {.lex_state = 6, .external_lex_state = 5},
  [58] = {.lex_state = 0, .external_lex_state = 7},
  [59] = {.lex_state = 0, .external_lex_state = 7},
  [60] = {.lex_state = 0, .external_lex_state = 7},
  [61] = {.lex_state = 6, .external_lex_state = 4},
  [62] = {.lex_state = 0, .external_lex_state = 7},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 3, .external_lex_state = 4},
  [65] = {.lex_state = 2, .external_lex_state = 4},
  [66] = {.lex_state = 0, .external_lex_state = 7},
  [67] = {.lex_state = 0, .external_lex_state = 8},
  [68] = {.lex_state = 0, .external_lex_state = 7},
  [69] = {.lex_state = 2, .external_lex_state = 4},
  [70] = {.lex_state = 0, .external_lex_state = 7},
  [71] = {.lex_state = 0, .external_lex_state = 7},
  [72] = {.lex_state = 3, .external_lex_state = 4},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 6, .external_lex_state = 4},
  [76] = {.lex_state = 6, .external_lex_state = 4},
  [77] = {.lex_state = 6, .external_lex_state = 4},
  [78] = {.lex_state = 0, .external_lex_state = 4},
  [79] = {.lex_state = 0, .external_lex_state = 8},
  [80] = {.lex_state = 0, .external_lex_state = 4},
  [81] = {.lex_state = 14, .external_lex_state = 4},
  [82] = {.lex_state = 0, .external_lex_state = 4},
  [83] = {.lex_state = 0, .external_lex_state = 4},
  [84] = {.lex_state = 0, .external_lex_state = 4},
  [85] = {.lex_state = 0, .external_lex_state = 4},
  [86] = {.lex_state = 0, .external_lex_state = 4},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 0, .external_lex_state = 4},
  [89] = {.lex_state = 0, .external_lex_state = 9},
  [90] = {.lex_state = 0, .external_lex_state = 10},
  [91] = {.lex_state = 0, .external_lex_state = 4},
  [92] = {.lex_state = 0, .external_lex_state = 4},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 0, .external_lex_state = 4},
  [95] = {.lex_state = 0, .external_lex_state = 9},
  [96] = {.lex_state = 14, .external_lex_state = 4},
  [97] = {.lex_state = 0, .external_lex_state = 4},
  [98] = {.lex_state = 0, .external_lex_state = 10},
  [99] = {.lex_state = 0, .external_lex_state = 4},
};

enum {
  ts_external_token__frontmatter_start = 0,
  ts_external_token__start_tag_name = 1,
  ts_external_token__script_start_tag_name = 2,
  ts_external_token__style_start_tag_name = 3,
  ts_external_token__end_tag_name = 4,
  ts_external_token_erroneous_end_tag_name = 5,
  ts_external_token_SLASH_GT = 6,
  ts_external_token__implicit_end_tag = 7,
  ts_external_token_raw_text = 8,
  ts_external_token_comment = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__frontmatter_start] = sym__frontmatter_start,
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [sym__frontmatter_start] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(87),
    [sym_doctype] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(4),
    [sym_script_start_tag] = STATE(60),
    [sym_style_start_tag] = STATE(59),
    [sym_self_closing_tag] = STATE(16),
    [sym_erroneous_end_tag] = STATE(8),
    [sym_frontmatter] = STATE(6),
    [aux_sym_fragment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [sym__frontmatter_start] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(25), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_end_tag,
    STATE(22), 1,
      sym_self_closing_tag,
    STATE(54), 1,
      sym_script_start_tag,
    STATE(58), 1,
      sym_style_start_tag,
    STATE(3), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [43] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym_text,
    ACTIONS(29), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(22), 1,
      sym_self_closing_tag,
    STATE(41), 1,
      sym_end_tag,
    STATE(54), 1,
      sym_script_start_tag,
    STATE(58), 1,
      sym_style_start_tag,
    STATE(7), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [86] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym_text,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(22), 1,
      sym_self_closing_tag,
    STATE(24), 1,
      sym_end_tag,
    STATE(54), 1,
      sym_script_start_tag,
    STATE(58), 1,
      sym_style_start_tag,
    STATE(5), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [129] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      sym_text,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(22), 1,
      sym_self_closing_tag,
    STATE(42), 1,
      sym_end_tag,
    STATE(54), 1,
      sym_script_start_tag,
    STATE(58), 1,
      sym_style_start_tag,
    STATE(7), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [172] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_style_start_tag,
    STATE(60), 1,
      sym_script_start_tag,
    STATE(10), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [212] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LT_BANG,
    ACTIONS(46), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_LT_SLASH,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(55), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(22), 1,
      sym_self_closing_tag,
    STATE(54), 1,
      sym_script_start_tag,
    STATE(58), 1,
      sym_style_start_tag,
    STATE(7), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [252] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_style_start_tag,
    STATE(60), 1,
      sym_script_start_tag,
    STATE(9), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [292] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      anon_sym_LT_BANG,
    ACTIONS(62), 1,
      anon_sym_LT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(68), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_style_start_tag,
    STATE(60), 1,
      sym_script_start_tag,
    STATE(9), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [332] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(57), 1,
      sym_text,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_style_start_tag,
    STATE(60), 1,
      sym_script_start_tag,
    STATE(9), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(75), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(77), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [398] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_GT,
    ACTIONS(83), 1,
      anon_sym_SLASH_GT,
    ACTIONS(85), 1,
      sym_attribute_name,
    STATE(26), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(87), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [428] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(91), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [441] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(97), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [454] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_attribute_name,
    ACTIONS(99), 1,
      anon_sym_GT,
    ACTIONS(101), 1,
      anon_sym_SLASH_GT,
    STATE(13), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [471] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(105), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [484] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(107), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [497] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_attribute_name,
    ACTIONS(99), 1,
      anon_sym_GT,
    ACTIONS(111), 1,
      anon_sym_SLASH_GT,
    STATE(35), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(113), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [527] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(97), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [540] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(119), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(113), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [566] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(119), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [579] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_attribute_name,
    ACTIONS(121), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(26), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [594] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(107), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [607] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(126), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [620] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(91), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(130), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [646] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(134), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(138), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(87), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(126), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [698] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_GT,
    ACTIONS(85), 1,
      sym_attribute_name,
    ACTIONS(142), 1,
      anon_sym_SLASH_GT,
    STATE(26), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(144), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [728] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(134), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [741] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(148), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [754] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(77), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [767] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(130), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [780] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(152), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [793] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(152), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [806] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(148), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [819] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_GT,
    ACTIONS(158), 1,
      sym_attribute_name,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [833] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_attribute_name,
    ACTIONS(160), 1,
      anon_sym_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [847] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_attribute_value,
    ACTIONS(164), 1,
      anon_sym_SQUOTE,
    ACTIONS(166), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_quoted_attribute_value,
  [863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_EQ,
    ACTIONS(168), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [875] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_GT,
    ACTIONS(172), 1,
      sym_attribute_name,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [889] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_attribute_name,
    ACTIONS(175), 1,
      anon_sym_GT,
    STATE(44), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [903] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_attribute_name,
    ACTIONS(177), 1,
      anon_sym_GT,
    STATE(45), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [917] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym_attribute_value,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    STATE(75), 1,
      sym_quoted_attribute_value,
  [933] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__start_tag_name,
    ACTIONS(187), 1,
      sym__script_start_tag_name,
    ACTIONS(189), 1,
      sym__style_start_tag_name,
  [946] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym__script_start_tag_name,
    ACTIONS(189), 1,
      sym__style_start_tag_name,
    ACTIONS(191), 1,
      sym__start_tag_name,
  [959] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LT_SLASH,
    ACTIONS(195), 1,
      sym_raw_text,
    STATE(19), 1,
      sym_end_tag,
  [972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [999] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LT_SLASH,
    ACTIONS(203), 1,
      sym_raw_text,
    STATE(15), 1,
      sym_end_tag,
  [1012] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LT_SLASH,
    ACTIONS(207), 1,
      sym_raw_text,
    STATE(29), 1,
      sym_end_tag,
  [1025] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LT_SLASH,
    ACTIONS(209), 1,
      sym_raw_text,
    STATE(27), 1,
      sym_end_tag,
  [1038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_EQ,
    ACTIONS(168), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1057] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LT_SLASH,
    STATE(38), 1,
      sym_end_tag,
  [1067] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_SQUOTE,
    ACTIONS(217), 1,
      aux_sym_quoted_attribute_value_token1,
  [1077] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 1,
      aux_sym_quoted_attribute_value_token2,
  [1087] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1095] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym__end_tag_name,
    ACTIONS(225), 1,
      sym_erroneous_end_tag_name,
  [1105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(229), 1,
      sym_raw_text,
  [1115] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    ACTIONS(233), 1,
      aux_sym_quoted_attribute_value_token2,
  [1125] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1141] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
    ACTIONS(239), 1,
      aux_sym_quoted_attribute_value_token1,
  [1151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LT_SLASH,
    STATE(39), 1,
      sym_end_tag,
  [1161] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LT_SLASH,
    STATE(12), 1,
      sym_end_tag,
  [1171] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1195] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LT_SLASH,
    STATE(43), 1,
      sym_end_tag,
  [1205] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(241), 1,
      sym__end_tag_name,
  [1215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_GT,
  [1222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      aux_sym_doctype_token1,
  [1229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_GT,
  [1236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_DASH_DASH_DASH,
  [1243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_SQUOTE,
  [1250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_GT,
  [1257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_GT,
  [1264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_GT,
  [1278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_erroneous_end_tag_name,
  [1285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym__end_tag_name,
  [1292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
  [1299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_SQUOTE,
  [1306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
  [1313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym__doctype,
  [1320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_erroneous_end_tag_name,
  [1327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      aux_sym_doctype_token1,
  [1334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_GT,
  [1341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym__end_tag_name,
  [1348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 172,
  [SMALL_STATE(7)] = 212,
  [SMALL_STATE(8)] = 252,
  [SMALL_STATE(9)] = 292,
  [SMALL_STATE(10)] = 332,
  [SMALL_STATE(11)] = 372,
  [SMALL_STATE(12)] = 385,
  [SMALL_STATE(13)] = 398,
  [SMALL_STATE(14)] = 415,
  [SMALL_STATE(15)] = 428,
  [SMALL_STATE(16)] = 441,
  [SMALL_STATE(17)] = 454,
  [SMALL_STATE(18)] = 471,
  [SMALL_STATE(19)] = 484,
  [SMALL_STATE(20)] = 497,
  [SMALL_STATE(21)] = 514,
  [SMALL_STATE(22)] = 527,
  [SMALL_STATE(23)] = 540,
  [SMALL_STATE(24)] = 553,
  [SMALL_STATE(25)] = 566,
  [SMALL_STATE(26)] = 579,
  [SMALL_STATE(27)] = 594,
  [SMALL_STATE(28)] = 607,
  [SMALL_STATE(29)] = 620,
  [SMALL_STATE(30)] = 633,
  [SMALL_STATE(31)] = 646,
  [SMALL_STATE(32)] = 659,
  [SMALL_STATE(33)] = 672,
  [SMALL_STATE(34)] = 685,
  [SMALL_STATE(35)] = 698,
  [SMALL_STATE(36)] = 715,
  [SMALL_STATE(37)] = 728,
  [SMALL_STATE(38)] = 741,
  [SMALL_STATE(39)] = 754,
  [SMALL_STATE(40)] = 767,
  [SMALL_STATE(41)] = 780,
  [SMALL_STATE(42)] = 793,
  [SMALL_STATE(43)] = 806,
  [SMALL_STATE(44)] = 819,
  [SMALL_STATE(45)] = 833,
  [SMALL_STATE(46)] = 847,
  [SMALL_STATE(47)] = 863,
  [SMALL_STATE(48)] = 875,
  [SMALL_STATE(49)] = 889,
  [SMALL_STATE(50)] = 903,
  [SMALL_STATE(51)] = 917,
  [SMALL_STATE(52)] = 933,
  [SMALL_STATE(53)] = 946,
  [SMALL_STATE(54)] = 959,
  [SMALL_STATE(55)] = 972,
  [SMALL_STATE(56)] = 981,
  [SMALL_STATE(57)] = 990,
  [SMALL_STATE(58)] = 999,
  [SMALL_STATE(59)] = 1012,
  [SMALL_STATE(60)] = 1025,
  [SMALL_STATE(61)] = 1038,
  [SMALL_STATE(62)] = 1049,
  [SMALL_STATE(63)] = 1057,
  [SMALL_STATE(64)] = 1067,
  [SMALL_STATE(65)] = 1077,
  [SMALL_STATE(66)] = 1087,
  [SMALL_STATE(67)] = 1095,
  [SMALL_STATE(68)] = 1105,
  [SMALL_STATE(69)] = 1115,
  [SMALL_STATE(70)] = 1125,
  [SMALL_STATE(71)] = 1133,
  [SMALL_STATE(72)] = 1141,
  [SMALL_STATE(73)] = 1151,
  [SMALL_STATE(74)] = 1161,
  [SMALL_STATE(75)] = 1171,
  [SMALL_STATE(76)] = 1179,
  [SMALL_STATE(77)] = 1187,
  [SMALL_STATE(78)] = 1195,
  [SMALL_STATE(79)] = 1205,
  [SMALL_STATE(80)] = 1215,
  [SMALL_STATE(81)] = 1222,
  [SMALL_STATE(82)] = 1229,
  [SMALL_STATE(83)] = 1236,
  [SMALL_STATE(84)] = 1243,
  [SMALL_STATE(85)] = 1250,
  [SMALL_STATE(86)] = 1257,
  [SMALL_STATE(87)] = 1264,
  [SMALL_STATE(88)] = 1271,
  [SMALL_STATE(89)] = 1278,
  [SMALL_STATE(90)] = 1285,
  [SMALL_STATE(91)] = 1292,
  [SMALL_STATE(92)] = 1299,
  [SMALL_STATE(93)] = 1306,
  [SMALL_STATE(94)] = 1313,
  [SMALL_STATE(95)] = 1320,
  [SMALL_STATE(96)] = 1327,
  [SMALL_STATE(97)] = 1334,
  [SMALL_STATE(98)] = 1341,
  [SMALL_STATE(99)] = 1348,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(99),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(53),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(95),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(94),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(52),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(89),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(9),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(47),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(61),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [257] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_astro_external_scanner_create(void);
void tree_sitter_astro_external_scanner_destroy(void *);
bool tree_sitter_astro_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_astro_external_scanner_serialize(void *, char *);
void tree_sitter_astro_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_astro(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_astro_external_scanner_create,
      tree_sitter_astro_external_scanner_destroy,
      tree_sitter_astro_external_scanner_scan,
      tree_sitter_astro_external_scanner_serialize,
      tree_sitter_astro_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
